version: '2'

volumes:
  satis:

services:
  satis:
    build:
      context: .
    hostname: local.satis.bostondrupal.com
    ports:
      - 8080:80
      - 9010:9010
    environment:
      GIT_USER_NAME: "Bryan Jiencke"
    working_dir: /var/www/satis
#    volumes:
#      - satis:/var/www/satis
