version: '2'

volumes:
  satis:

services:
  satis:
    build:
      context: .
    hostname: satis.bostondrupal.com
    ports:
      - 0:22
      - 0:80
      - 0:443
      - 9010:9010
    environment:
      GIT_USER_NAME: "Bryan Jiencke"
    working_dir: /var/satis
    volumes:
      - satis:/var/satis
